version: 2
jobs:
  build:
    branches:
      only:
        - master
        - develop

    docker:
      - image: ubuntu:trusty

    steps:
      - checkout

      - run:
          name: Install package dependencies
          command: sudo apt-get update && sudo apt-get install -y build-essential cmake openmpi-bin libopenmpi-dev python-dev libvtk6 libvtk6-dev

      - run:
          name: Configure LIGGGHTS build
          command: mkdir -p build && cd build && cmake ../src/

      - run:
          name: Build LIGGGHTS
          command: cd build && make -j2
          no_output_timeout: 30m
